services:
  app:
    image: serversideup/php:8.3-fpm-nginx
    working_dir: /var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-sanglah_sop}
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - AUTORUN_LARAVEL_MIGRATION=true
    ports:
      - "8000:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: '${DB_DATABASE:-sanglah_sop}'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
